// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void pwdup_Animation(lv_obj_t * TargetObject, int delay);
void pwddown_Animation(lv_obj_t * TargetObject, int delay);
void loading_Animation(lv_obj_t * TargetObject, int delay);
void moveright_Animation(lv_obj_t * TargetObject, int delay);
void moveleft_Animation(lv_obj_t * TargetObject, int delay);
void spin_Animation(lv_obj_t * TargetObject, int delay);
void listup_Animation(lv_obj_t * TargetObject, int delay);
void listdown_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_mainpage
void ui_mainpage_screen_init(void);
void ui_event_mainpage(lv_event_t * e);
lv_obj_t * ui_mainpage;
void ui_event_weather(lv_event_t * e);
lv_obj_t * ui_weather;
void ui_event_sensor(lv_event_t * e);
lv_obj_t * ui_sensor;
// void ui_event_audio(lv_event_t * e);
// lv_obj_t * ui_audio;
void ui_event_music(lv_event_t * e);
lv_obj_t * ui_music;
lv_obj_t * ui_gravity;
void ui_event_direction(lv_event_t * e);
lv_obj_t * ui_direction;
void ui_event_setting(lv_event_t * e);
lv_obj_t * ui_setting;

// SCREEN: ui_servopage
void ui_servopage_screen_init(void);
lv_obj_t * ui_servopage;
void ui_event_degreearc(lv_event_t * e);
lv_obj_t * ui_degreearc;
void ui_event_servoback(lv_event_t * e);
lv_obj_t * ui_servoback;
lv_obj_t * ui_degreenum;

// SCREEN: ui_sensorpage
void ui_sensorpage_screen_init(void);
void ui_event_sensorpage(lv_event_t * e);
lv_obj_t * ui_sensorpage;
lv_obj_t * ui_aht20panel;
lv_obj_t * ui_aht20temp;
lv_obj_t * ui_aht20tempnum;
lv_obj_t * ui_aht20label;
lv_obj_t * ui_aht20humi;
lv_obj_t * ui_aht20huminum;
lv_obj_t * ui_bmp280panel;
lv_obj_t * ui_bmp280label;
lv_obj_t * ui_bmptempnum;
lv_obj_t * ui_bmppressnum;
lv_obj_t * ui_bmppress;
lv_obj_t * ui_bmptemp;
lv_obj_t * ui_bmpalti;
lv_obj_t * ui_bmpaltnum;
void ui_event_sensorback(lv_event_t * e);
lv_obj_t * ui_sensorback;

// SCREEN: ui_weathercpage
void ui_weathercpage_screen_init(void);
void ui_event_weathercpage(lv_event_t * e);
lv_obj_t * ui_weathercpage;
lv_obj_t * ui_statepanel;
lv_obj_t * ui_outhumi;
lv_obj_t * ui_outtemp;
lv_obj_t * ui_tempimage2;
lv_obj_t * ui_humiimage2;
lv_obj_t * ui_pressimage2;
lv_obj_t * ui_winddirimage1;
lv_obj_t * ui_outpress;
lv_obj_t * ui_winddir;
lv_obj_t * ui_windscaleimage1;
lv_obj_t * ui_windscale;
lv_obj_t * ui_visimage1;
lv_obj_t * ui_vis;
lv_obj_t * ui_time;
lv_obj_t * ui_weathericon;
lv_obj_t * ui_date;
lv_obj_t * ui_week;
lv_obj_t * ui_weatherstate;
lv_obj_t * ui_feeltemp;
lv_obj_t * ui_category;
void ui_event_weatherback(lv_event_t * e);
lv_obj_t * ui_weatherback;
void ui_event_weatherfor(lv_event_t * e);
lv_obj_t * ui_weatherfor;

// SCREEN: ui_musicpage
void ui_musicpage_screen_init(void);
void ui_event_musicpage(lv_event_t * e);
lv_obj_t * ui_musicpage;
lv_obj_t * ui_playdisc;
lv_obj_t * ui_prevmusic;
lv_obj_t * ui_playtype;
void ui_event_musicstate(lv_event_t * e);
lv_obj_t * ui_musicstate;
lv_obj_t * ui_nextmusic;
lv_obj_t * ui_musicline;
void ui_event_musicback(lv_event_t * e);
lv_obj_t * ui_musicback;
void ui_event_musiclist(lv_event_t * e);
lv_obj_t * ui_musiclist;
lv_obj_t * ui_musicinfo;
lv_obj_t * ui_listpanel;
void ui_event_listplay(lv_event_t * e);
lv_obj_t * ui_listplay;
lv_obj_t * ui_musicname;
lv_obj_t * ui_listroller;

// SCREEN: ui_settingpage
void ui_settingpage_screen_init(void);
void ui_event_settingpage(lv_event_t * e);
lv_obj_t * ui_settingpage;
lv_obj_t * ui_wifi;
void ui_event_wifilist(lv_event_t * e);
lv_obj_t * ui_wifilist;
void ui_event_scanWifi(lv_event_t * e);
lv_obj_t * ui_scanWifi;
lv_obj_t * ui_blkpanel;
void ui_event_blkslider(lv_event_t * e);
lv_obj_t * ui_blkslider;
// lv_obj_t * ui_blknum;
lv_obj_t * ui_blk;
lv_obj_t * ui_volumepanel;
void ui_event_volumeslider(lv_event_t * e);
lv_obj_t * ui_volumeslider;
lv_obj_t * ui_volume;
lv_obj_t * ui_PWDINPUT;
lv_obj_t * ui_pwdkey;
void ui_event_connectWifi(lv_event_t * e);
lv_obj_t * ui_connectWifi;
lv_obj_t * ui_pwdarea;
lv_obj_t * ui_load;
void ui_event_settingback(lv_event_t * e);
lv_obj_t * ui_settingback;

// SCREEN: ui_airqpage
void ui_airqpage_screen_init(void);
void ui_event_airqpage(lv_event_t * e);
lv_obj_t * ui_airqpage;
lv_obj_t * ui_airqualitylist;
lv_obj_t * ui_aairlabel;
void ui_event_airback(lv_event_t * e);
lv_obj_t * ui_airback;
void ui_event_airfor(lv_event_t * e);
lv_obj_t * ui_airfor;

// SCREEN: ui_futurewpage
void ui_futurewpage_screen_init(void);
void ui_event_futurewpage(lv_event_t * e);
void ui_event_futureback(lv_event_t * e);
lv_obj_t * ui_futureback;
void ui_event_futurefor(lv_event_t * e);
lv_obj_t * ui_futurefor;
lv_obj_t * ui_futurewpage;
lv_obj_t * ui_fwlabel;
lv_obj_t * ui_weatherpanel;
lv_obj_t * ui_day1;
lv_obj_t * ui_day1label;
lv_obj_t * ui_day1temp;
lv_obj_t * ui_day1icon;
lv_obj_t * ui_day2;
lv_obj_t * ui_day2label;
lv_obj_t * ui_day2temp;
lv_obj_t * ui_day2icon;
lv_obj_t * ui_day3;
lv_obj_t * ui_day3label;
lv_obj_t * ui_day3temp;
lv_obj_t * ui_day3icon;
lv_obj_t * ui_day4;
lv_obj_t * ui_day4label;
lv_obj_t * ui_day4temp;
lv_obj_t * ui_day4icon;
lv_obj_t * ui_day5;
lv_obj_t * ui_day5label;
lv_obj_t * ui_day5temp;
lv_obj_t * ui_day5icon;
lv_obj_t * ui_day6;
lv_obj_t * ui_day6label;
lv_obj_t * ui_day6temp;
lv_obj_t * ui_day6icon;
lv_obj_t * ui_day7;
lv_obj_t * ui_day7label;
lv_obj_t * ui_day7temp;
lv_obj_t * ui_day7icon;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void pwdup_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 240, 36);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void pwddown_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 36, 240);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void loading_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void moveright_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, -300, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void moveleft_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 300, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

void spin_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 5);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void listup_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 300, 20);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void listdown_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 20, 250);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_settingpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_direction(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_servopage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_weathercpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_sensor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_sensorpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }//ui_sensorpage
}
// void ui_event_audio(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t * target = lv_event_get_target(e);
//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(ui_settingpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
//     }//ui_sensorpage
// }
void ui_event_music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_musicpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_settingpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);//ui_settingpage
    }
}
void ui_event_sensorpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_degreearc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_degreenum, target, "", "°");
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        servo_degree(e);
    }
}
void ui_event_servoback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_sensorback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_musicpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 20);
    }
}
void ui_event_musicstate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        // spin_Animation(ui_playdisc, 0);
    }
}
void ui_event_musicback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_musiclist(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        listup_Animation(ui_listpanel, 0);
    }
}
void ui_event_listplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        listdown_Animation(ui_listpanel, 0);
    }
}

void ui_event_settingback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_airback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_weathercpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_airfor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_futurewpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_futureback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_airqpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_futurefor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_weathercpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_weatherback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_weatherfor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_airqpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_weathercpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_airqpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_settingpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_mainpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 20);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        moveright_Animation(ui_wifi, 50);
        moveright_Animation(ui_volumepanel, 0);
        moveleft_Animation(ui_blkpanel, 0);
    }
}
void ui_event_wifilist(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        pwdup_Animation(ui_PWDINPUT, 20);
        _ui_keyboard_set_target(ui_pwdkey,  ui_pwdarea);
    }
}
void ui_event_scanWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    // if(event_code == LV_EVENT_CLICKED) {
    //     scanWifiN(e);
    // }
    // if(event_code == LV_EVENT_CLICKED) {
    //     loading_Animation(ui_load, 0);
    // }
}
void ui_event_blkslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        set_back_brightness(e);
        // _ui_slider_set_text_value(ui_blknum, target, "", "%");
        _ui_image_set_property(ui_blk, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_icon_setting_blkdd_png);
    }
}
void ui_event_volumeslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_image_set_property(ui_volume, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_icon_setting_volume_png);
    }
}
void ui_event_connectWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    // if(event_code == LV_EVENT_CLICKED) {
    //     connectWifi(e);
    // }
    if(event_code == LV_EVENT_CLICKED) {
        wifi_connect();
        pwddown_Animation(ui_PWDINPUT, 20);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_load, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_airqpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_weathercpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_futurewpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_futurewpage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        // lv_indev_wait_release(lv_indev_get_act());
        // _ui_screen_change(ui_airqpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainpage_screen_init();
    ui_sensorpage_screen_init();
    ui_weathercpage_screen_init();
    ui_musicpage_screen_init();
    ui_settingpage_screen_init();
    ui_servopage_screen_init();
    ui_airqpage_screen_init();
    ui_futurewpage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainpage);
}
