// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

extern void wifi_connect();
void pwdup_Animation(lv_obj_t * TargetObject, int delay);
void pwddown_Animation(lv_obj_t * TargetObject, int delay);
void loading_Animation(lv_obj_t * TargetObject, int delay);
void moveright_Animation(lv_obj_t * TargetObject, int delay);
void moveleft_Animation(lv_obj_t * TargetObject, int delay);
void spin_Animation(lv_obj_t * TargetObject, int delay);
void listup_Animation(lv_obj_t * TargetObject, int delay);
void listdown_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_mainpage
void ui_mainpage_screen_init(void);
void ui_event_mainpage(lv_event_t * e);
extern lv_obj_t * ui_mainpage;
void ui_event_weather(lv_event_t * e);
extern lv_obj_t * ui_weather;
void ui_event_sensor(lv_event_t * e);
extern lv_obj_t * ui_sensor;
// void ui_event_audio(lv_event_t * e);
// extern lv_obj_t * ui_audio;
void ui_event_music(lv_event_t * e);
extern lv_obj_t * ui_music;
extern lv_obj_t * ui_gravity;
void ui_event_direction(lv_event_t * e);
extern lv_obj_t * ui_direction;
void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
void ui_event_settingback(lv_event_t * e);
extern lv_obj_t * ui_settingback;

// SCREEN: ui_servopage
void ui_servopage_screen_init(void);
extern lv_obj_t * ui_servopage;
void ui_event_degreearc(lv_event_t * e);
extern lv_obj_t * ui_degreearc;
void ui_event_servoback(lv_event_t * e);
extern lv_obj_t * ui_servoback;
extern lv_obj_t * ui_degreenum;

// SCREEN: ui_sensorpage
void ui_sensorpage_screen_init(void);
void ui_event_sensorpage(lv_event_t * e);
extern lv_obj_t * ui_sensorpage;
extern lv_obj_t * ui_aht20panel;
extern lv_obj_t * ui_aht20temp;
extern lv_obj_t * ui_aht20tempnum;
extern lv_obj_t * ui_aht20label;
extern lv_obj_t * ui_aht20humi;
extern lv_obj_t * ui_aht20huminum;
extern lv_obj_t * ui_bmp280panel;
extern lv_obj_t * ui_bmp280label;
extern lv_obj_t * ui_bmptempnum;
extern lv_obj_t * ui_bmppressnum;
extern lv_obj_t * ui_bmppress;
extern lv_obj_t * ui_bmptemp;
extern lv_obj_t * ui_bmpalti;
extern lv_obj_t * ui_bmpaltnum;
void ui_event_sensorback(lv_event_t * e);
extern lv_obj_t * ui_sensorback;

// SCREEN: ui_weathercpage
void ui_weathercpage_screen_init(void);
void ui_event_weathercpage(lv_event_t * e);
extern lv_obj_t * ui_weathercpage;
extern lv_obj_t * ui_statepanel;
extern lv_obj_t * ui_outhumi;
extern lv_obj_t * ui_outtemp;
extern lv_obj_t * ui_tempimage2;
extern lv_obj_t * ui_humiimage2;
extern lv_obj_t * ui_pressimage2;
extern lv_obj_t * ui_winddirimage1;
extern lv_obj_t * ui_outpress;
extern lv_obj_t * ui_winddir;
extern lv_obj_t * ui_windscaleimage1;
extern lv_obj_t * ui_windscale;
extern lv_obj_t * ui_visimage1;
extern lv_obj_t * ui_vis;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_weathericon;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_weatherstate;
extern lv_obj_t * ui_feeltemp;
extern lv_obj_t * ui_category;
void ui_event_weatherback(lv_event_t * e);
extern lv_obj_t * ui_weatherback;
void ui_event_weatherfor(lv_event_t * e);
extern lv_obj_t * ui_weatherfor;

// SCREEN: ui_musicpage
void ui_musicpage_screen_init(void);
void ui_event_musicpage(lv_event_t * e);
extern lv_obj_t * ui_musicpage;
extern lv_obj_t * ui_playdisc;
extern lv_obj_t * ui_prevmusic;
extern lv_obj_t * ui_playtype;
void ui_event_musicstate(lv_event_t * e);
extern lv_obj_t * ui_musicstate;
extern lv_obj_t * ui_nextmusic;
extern lv_obj_t * ui_musicline;
void ui_event_musicback(lv_event_t * e);
extern lv_obj_t * ui_musicback;
void ui_event_musiclist(lv_event_t * e);
extern lv_obj_t * ui_musiclist;
extern lv_obj_t * ui_musicinfo;
extern lv_obj_t * ui_listpanel;
void ui_event_listplay(lv_event_t * e);
extern lv_obj_t * ui_listplay;
extern lv_obj_t * ui_musicname;
extern lv_obj_t * ui_listroller;

// SCREEN: ui_settingpage
void ui_settingpage_screen_init(void);
void ui_event_settingpage(lv_event_t * e);
extern lv_obj_t * ui_settingpage;
extern lv_obj_t * ui_wifi;
void ui_event_wifilist(lv_event_t * e);
extern lv_obj_t * ui_wifilist;
void ui_event_scanWifi(lv_event_t * e);
extern lv_obj_t * ui_scanWifi;
extern lv_obj_t * ui_blkpanel;
void ui_event_blkslider(lv_event_t * e);
extern lv_obj_t * ui_blkslider;
// extern lv_obj_t * ui_blknum;
extern lv_obj_t * ui_blk;
extern lv_obj_t * ui_volumepanel;
void ui_event_volumeslider(lv_event_t * e);
extern lv_obj_t * ui_volumeslider;
extern lv_obj_t * ui_volume;
extern lv_obj_t * ui_PWDINPUT;
extern lv_obj_t * ui_pwdkey;
void ui_event_connectWifi(lv_event_t * e);
extern lv_obj_t * ui_connectWifi;
extern lv_obj_t * ui_pwdarea;
extern lv_obj_t * ui_load;

// SCREEN: ui_airqpage
void ui_airqpage_screen_init(void);
void ui_event_airqpage(lv_event_t * e);
extern lv_obj_t * ui_airqpage;
extern lv_obj_t * ui_airqualitylist;
extern lv_obj_t * ui_aairlabel;
void ui_event_airback(lv_event_t * e);
extern lv_obj_t * ui_airback;
void ui_event_airfor(lv_event_t * e);
extern lv_obj_t * ui_airfor;

// SCREEN: ui_futurewpage
void ui_futurewpage_screen_init(void);
void ui_event_futurewpage(lv_event_t * e);
void ui_event_futureback(lv_event_t * e);
extern lv_obj_t * ui_futureback;
void ui_event_futurefor(lv_event_t * e);
extern lv_obj_t * ui_futurefor;
extern lv_obj_t * ui_futurewpage;
extern lv_obj_t * ui_fwlabel;
extern lv_obj_t * ui_weatherpanel;
extern lv_obj_t * ui_day1;
extern lv_obj_t * ui_day1label;
extern lv_obj_t * ui_day1temp;
extern lv_obj_t * ui_day1icon;
extern lv_obj_t * ui_day2;
extern lv_obj_t * ui_day2label;
extern lv_obj_t * ui_day2temp;
extern lv_obj_t * ui_day2icon;
extern lv_obj_t * ui_day3;
extern lv_obj_t * ui_day3label;
extern lv_obj_t * ui_day3temp;
extern lv_obj_t * ui_day3icon;
extern lv_obj_t * ui_day4;
extern lv_obj_t * ui_day4label;
extern lv_obj_t * ui_day4temp;
extern lv_obj_t * ui_day4icon;
extern lv_obj_t * ui_day5;
extern lv_obj_t * ui_day5label;
extern lv_obj_t * ui_day5temp;
extern lv_obj_t * ui_day5icon;
extern lv_obj_t * ui_day6;
extern lv_obj_t * ui_day6label;
extern lv_obj_t * ui_day6temp;
extern lv_obj_t * ui_day6icon;
extern lv_obj_t * ui_day7;
extern lv_obj_t * ui_day7label;
extern lv_obj_t * ui_day7temp;
extern lv_obj_t * ui_day7icon;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_icon_weather_png);    // assets\ICON\weather.png
LV_IMG_DECLARE(ui_img_icon_sensor_png);    // assets\ICON\sensor.png
LV_IMG_DECLARE(ui_img_icon_audio_png);    // assets\ICON\audio.png
LV_IMG_DECLARE(ui_img_icon_gravity_png);    // assets\ICON\gravity.png
LV_IMG_DECLARE(ui_img_icon_direction_png);    // assets\ICON\direction.png
LV_IMG_DECLARE(ui_img_icon_setting_png);    // assets\ICON\setting.png
LV_IMG_DECLARE(ui_img_icon_temp_png);    // assets\ICON\temp.png
LV_IMG_DECLARE(ui_img_icon_humi_png);    // assets\ICON\humi.png
LV_IMG_DECLARE(ui_img_icon_pressure_png);    // assets\ICON\pressure.png
LV_IMG_DECLARE(ui_img_icon_winddir_png);    // assets\ICON\winddir.png
LV_IMG_DECLARE(ui_img_icon_windspeed_png);    // assets\ICON\windspeed.png
LV_IMG_DECLARE(ui_img_icon_vis_png);    // assets\ICON\vis.png
LV_IMG_DECLARE(ui_img_icon_weather_mai_png);    // assets\ICON\WEATHER\mai.png
LV_IMG_DECLARE(ui_img_icon_weather_cloudy_png);    // assets\ICON\WEATHER\cloudy.png
LV_IMG_DECLARE(ui_img_icon_altitude_png);    // assets\ICON\Altitude.png
LV_IMG_DECLARE(ui_img_icon_backward_png);    // assets\ICON\backward.png
LV_IMG_DECLARE(ui_img_icon_forward_png);    // assets\ICON\forward.png

LV_FONT_DECLARE(ui_font_AS30);
LV_FONT_DECLARE(ui_font_iconfont);
LV_FONT_DECLARE(ui_font_PM30);
LV_FONT_DECLARE(ui_font_PM40);
LV_FONT_DECLARE(ui_font_SY15);
LV_FONT_DECLARE(ui_font_SY20);

// WEATHER
LV_IMG_DECLARE(ui_img_icon_weather_cloudy_png);    // assets\ICON\WEATHER\cloudy.png
LV_IMG_DECLARE(ui_img_icon_weather_cold_png);    // assets\ICON\WEATHER\cold.png
LV_IMG_DECLARE(ui_img_icon_weather_foggy_png);    // assets\ICON\WEATHER\foggy.png
LV_IMG_DECLARE(ui_img_icon_weather_heavyrain_png);    // assets\ICON\WEATHER\heavyrain.png
LV_IMG_DECLARE(ui_img_icon_weather_hot_png);    // assets\ICON\WEATHER\hot.png
LV_IMG_DECLARE(ui_img_icon_weather_lightrain_png);    // assets\ICON\WEATHER\lightrain.png
LV_IMG_DECLARE(ui_img_icon_weather_mist_png);    // assets\ICON\WEATHER\mist.png
LV_IMG_DECLARE(ui_img_icon_weather_na_png);    // assets\ICON\WEATHER\na.png
LV_IMG_DECLARE(ui_img_icon_weather_overcast_png);    // assets\ICON\WEATHER\overcast.png
LV_IMG_DECLARE(ui_img_icon_weather_sand_png);    // assets\ICON\WEATHER\sand.png
LV_IMG_DECLARE(ui_img_icon_weather_sandstorm_png);    // assets\ICON\WEATHER\sandstorm.png
LV_IMG_DECLARE(ui_img_icon_weather_snow_png);    // assets\ICON\WEATHER\snow.png
LV_IMG_DECLARE(ui_img_icon_weather_sunny_png);    // assets\ICON\WEATHER\sunny.png
LV_IMG_DECLARE(ui_img_icon_weather_thunderrain_png);    // assets\ICON\WEATHER\thunderrain.png
LV_IMG_DECLARE(ui_img_icon_weather_shower_png);    // assets\ICON\WEATHER\thunderrain.png

// MUSIC
LV_IMG_DECLARE(ui_img_icon_music_musicicon_png);    // assets\ICON\MUSIC\musicicon.png
LV_IMG_DECLARE(ui_img_icon_music_music1_png);    // assets\ICON\MUSIC\music1.png
LV_IMG_DECLARE(ui_img_icon_music_prevm_png);    // assets\ICON\MUSIC\prevm.png
LV_IMG_DECLARE(ui_img_icon_music_cirm_png);    // assets\ICON\MUSIC\cirm.png
LV_IMG_DECLARE(ui_img_icon_music_pause_png);    // assets\ICON\MUSIC\pause.png
LV_IMG_DECLARE(ui_img_icon_music_nextm_png);    // assets\ICON\MUSIC\nextm.png
LV_IMG_DECLARE(ui_img_icon_music_musicback_png);    // assets\ICON\MUSIC\musicback.png
LV_IMG_DECLARE(ui_img_icon_music_musiclist_png);    // assets\ICON\MUSIC\musiclist.png
LV_IMG_DECLARE(ui_img_icon_music_play_png);    // assets\ICON\MUSIC\play.png

// SETTING
LV_IMG_DECLARE(ui_img_icon_setting_wifi_png);    // assets\ICON\SETTING\WIFI.png
LV_IMG_DECLARE(ui_img_icon_setting_blkd_png);    // assets\ICON\SETTING\BLKD.png
LV_IMG_DECLARE(ui_img_icon_setting_blkl_png);    // assets\ICON\SETTING\BLKL.png
LV_IMG_DECLARE(ui_img_icon_setting_blkdd_png);    // assets\ICON\SETTING\blkdd.png
LV_IMG_DECLARE(ui_img_icon_setting_volume_png);    // assets\ICON\SETTING\volume.png
LV_IMG_DECLARE(ui_img_icon_setting_volume1_png);    // assets\ICON\SETTING\volume1.png
LV_IMG_DECLARE(ui_img_icon_setting_volume2_png);    // assets\ICON\SETTING\volume2.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
