// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_futurewpage_screen_init(void)
{
    ui_futurewpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_futurewpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_futurewpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_futurewpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fwlabel = lv_label_create(ui_futurewpage);
    lv_obj_set_width(ui_fwlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fwlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fwlabel, 0);
    lv_obj_set_y(ui_fwlabel, -85);
    lv_obj_set_align(ui_fwlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fwlabel, "天气预报");
    lv_obj_set_style_text_color(ui_fwlabel, lv_color_hex(0xFB9441), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_fwlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_fwlabel, &ui_font_PM30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherpanel = lv_obj_create(ui_futurewpage);
    lv_obj_set_width(ui_weatherpanel, 313);
    lv_obj_set_height(ui_weatherpanel, 183);
    lv_obj_set_x(ui_weatherpanel, 0);
    lv_obj_set_y(ui_weatherpanel, 24);
    lv_obj_set_align(ui_weatherpanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_weatherpanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_weatherpanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    // lv_obj_clear_flag(ui_weatherpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weatherpanel, lv_color_hex(0x202C39), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weatherpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weatherpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day1, 90);
    lv_obj_set_height(ui_day1, 151);
    lv_obj_set_x(ui_day1, lv_pct(-36));
    lv_obj_set_y(ui_day1, lv_pct(0));
    lv_obj_set_align(ui_day1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day1, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1label = lv_label_create(ui_day1);
    lv_obj_set_width(ui_day1label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day1label, -3);
    lv_obj_set_y(ui_day1label, 9);
    lv_obj_set_align(ui_day1label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day1label, "多云");
    lv_obj_set_style_text_color(ui_day1label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day1label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day1label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1temp = lv_label_create(ui_day1);
    lv_obj_set_width(ui_day1temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day1temp, 0);
    lv_obj_set_y(ui_day1temp, 40);
    lv_obj_set_align(ui_day1temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day1temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day1temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day1temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day1temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day1icon = lv_img_create(ui_day1);
    lv_img_set_src(ui_day1icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day1icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day1icon, 0);
    lv_obj_set_y(ui_day1icon, -36);
    lv_obj_set_align(ui_day1icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day1icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day1icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day1icon, 200);

    ui_day2 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day2, 90);
    lv_obj_set_height(ui_day2, 151);
    lv_obj_set_x(ui_day2, lv_pct(60));
    lv_obj_set_y(ui_day2, lv_pct(0));
    lv_obj_set_align(ui_day2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day2, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2label = lv_label_create(ui_day2);
    lv_obj_set_width(ui_day2label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2label, -3);
    lv_obj_set_y(ui_day2label, 9);
    lv_obj_set_align(ui_day2label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day2label, "多云");
    lv_obj_set_style_text_color(ui_day2label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day2label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day2label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2temp = lv_label_create(ui_day2);
    lv_obj_set_width(ui_day2temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2temp, 0);
    lv_obj_set_y(ui_day2temp, 40);
    lv_obj_set_align(ui_day2temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day2temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day2temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day2temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day2temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day2icon = lv_img_create(ui_day2);
    lv_img_set_src(ui_day2icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day2icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day2icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day2icon, 0);
    lv_obj_set_y(ui_day2icon, -36);
    lv_obj_set_align(ui_day2icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day2icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day2icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day2icon, 200);

    ui_day3 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day3, 90);
    lv_obj_set_height(ui_day3, 151);
    lv_obj_set_x(ui_day3, lv_pct(156));
    lv_obj_set_y(ui_day3, lv_pct(0));
    lv_obj_set_align(ui_day3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day3, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3label = lv_label_create(ui_day3);
    lv_obj_set_width(ui_day3label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3label, -3);
    lv_obj_set_y(ui_day3label, 9);
    lv_obj_set_align(ui_day3label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day3label, "多云");
    lv_obj_set_style_text_color(ui_day3label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day3label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day3label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3temp = lv_label_create(ui_day3);
    lv_obj_set_width(ui_day3temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3temp, 0);
    lv_obj_set_y(ui_day3temp, 40);
    lv_obj_set_align(ui_day3temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day3temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day3temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day3temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day3temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day3icon = lv_img_create(ui_day3);
    lv_img_set_src(ui_day3icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day3icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day3icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day3icon, 0);
    lv_obj_set_y(ui_day3icon, -36);
    lv_obj_set_align(ui_day3icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day3icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day3icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day3icon, 200);

    ui_day4 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day4, 90);
    lv_obj_set_height(ui_day4, 151);
    lv_obj_set_x(ui_day4, lv_pct(252));
    lv_obj_set_y(ui_day4, lv_pct(0));
    lv_obj_set_align(ui_day4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day4, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day4label = lv_label_create(ui_day4);
    lv_obj_set_width(ui_day4label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day4label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day4label, -3);
    lv_obj_set_y(ui_day4label, 9);
    lv_obj_set_align(ui_day4label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day4label, "多云");
    lv_obj_set_style_text_color(ui_day4label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day4label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day4label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day4temp = lv_label_create(ui_day4);
    lv_obj_set_width(ui_day4temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day4temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day4temp, 0);
    lv_obj_set_y(ui_day4temp, 40);
    lv_obj_set_align(ui_day4temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day4temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day4temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day4temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day4temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day4icon = lv_img_create(ui_day4);
    lv_img_set_src(ui_day4icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day4icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day4icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day4icon, 0);
    lv_obj_set_y(ui_day4icon, -36);
    lv_obj_set_align(ui_day4icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day4icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day4icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day4icon, 200);

    ui_day5 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day5, 90);
    lv_obj_set_height(ui_day5, 151);
    lv_obj_set_x(ui_day5, lv_pct(348));
    lv_obj_set_y(ui_day5, lv_pct(0));
    lv_obj_set_align(ui_day5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day5, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day5label = lv_label_create(ui_day5);
    lv_obj_set_width(ui_day5label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day5label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day5label, -3);
    lv_obj_set_y(ui_day5label, 9);
    lv_obj_set_align(ui_day5label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day5label, "多云");
    lv_obj_set_style_text_color(ui_day5label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day5label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day5label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day5temp = lv_label_create(ui_day5);
    lv_obj_set_width(ui_day5temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day5temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day5temp, 0);
    lv_obj_set_y(ui_day5temp, 40);
    lv_obj_set_align(ui_day5temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day5temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day5temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day5temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day5temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day5icon = lv_img_create(ui_day5);
    lv_img_set_src(ui_day5icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day5icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day5icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day5icon, 0);
    lv_obj_set_y(ui_day5icon, -36);
    lv_obj_set_align(ui_day5icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day5icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day5icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day5icon, 200);

    ui_day6 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day6, 90);
    lv_obj_set_height(ui_day6, 151);
    lv_obj_set_x(ui_day6, lv_pct(444));
    lv_obj_set_y(ui_day6, lv_pct(0));
    lv_obj_set_align(ui_day6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day6, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day6label = lv_label_create(ui_day6);
    lv_obj_set_width(ui_day6label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day6label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day6label, -3);
    lv_obj_set_y(ui_day6label, 9);
    lv_obj_set_align(ui_day6label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day6label, "多云");
    lv_obj_set_style_text_color(ui_day6label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day6label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day6label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day6temp = lv_label_create(ui_day6);
    lv_obj_set_width(ui_day6temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day6temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day6temp, 0);
    lv_obj_set_y(ui_day6temp, 40);
    lv_obj_set_align(ui_day6temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day6temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day6temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day6temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day6temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day6icon = lv_img_create(ui_day6);
    lv_img_set_src(ui_day6icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day6icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day6icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day6icon, 0);
    lv_obj_set_y(ui_day6icon, -36);
    lv_obj_set_align(ui_day6icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day6icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day6icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day6icon, 200);

    ui_day7 = lv_obj_create(ui_weatherpanel);
    lv_obj_set_width(ui_day7, 90);
    lv_obj_set_height(ui_day7, 151);
    lv_obj_set_x(ui_day7, lv_pct(540));
    lv_obj_set_y(ui_day7, lv_pct(0));
    lv_obj_set_align(ui_day7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_day7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_day7, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_day7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day7label = lv_label_create(ui_day7);
    lv_obj_set_width(ui_day7label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day7label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day7label, -3);
    lv_obj_set_y(ui_day7label, 9);
    lv_obj_set_align(ui_day7label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day7label, "多云");
    lv_obj_set_style_text_color(ui_day7label, lv_color_hex(0x4A89FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day7label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day7label, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day7temp = lv_label_create(ui_day7);
    lv_obj_set_width(ui_day7temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day7temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day7temp, 0);
    lv_obj_set_y(ui_day7temp, 40);
    lv_obj_set_align(ui_day7temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day7temp, "10~15℃");
    lv_obj_set_style_text_color(ui_day7temp, lv_color_hex(0xF87E3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day7temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day7temp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day7icon = lv_img_create(ui_day7);
    lv_img_set_src(ui_day7icon, &ui_img_icon_weather_cloudy_png);
    lv_obj_set_width(ui_day7icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day7icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day7icon, 0);
    lv_obj_set_y(ui_day7icon, -36);
    lv_obj_set_align(ui_day7icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_day7icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_day7icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_day7icon, 200);

    ui_futureback = lv_imgbtn_create(ui_futurewpage);
    lv_imgbtn_set_src(ui_futureback, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_backward_png, NULL);
    lv_obj_set_height(ui_futureback, 32);
    lv_obj_set_width(ui_futureback, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_futureback, 10);
    lv_obj_set_y(ui_futureback, 10);
    lv_obj_set_align(ui_futureback, LV_ALIGN_TOP_LEFT);

    ui_futurefor = lv_imgbtn_create(ui_futurewpage);
    lv_imgbtn_set_src(ui_futurefor, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_forward_png, NULL);
    lv_obj_set_height(ui_futurefor, 32);
    lv_obj_set_width(ui_futurefor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_futurefor, -10);
    lv_obj_set_y(ui_futurefor, 10);
    lv_obj_set_align(ui_futurefor, LV_ALIGN_TOP_RIGHT);

    lv_obj_add_event_cb(ui_futurefor, ui_event_futurefor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_futureback, ui_event_futureback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_futurewpage, ui_event_futurewpage, LV_EVENT_ALL, NULL);

}
