// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_sensorpage_screen_init(void)
{
    ui_sensorpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_sensorpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sensorpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sensorpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aht20panel = lv_obj_create(ui_sensorpage);
    lv_obj_set_width(ui_aht20panel, 150);
    lv_obj_set_height(ui_aht20panel, 180);
    lv_obj_set_x(ui_aht20panel, 5);
    lv_obj_set_y(ui_aht20panel, 5);
    lv_obj_clear_flag(ui_aht20panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aht20panel, lv_color_hex(0x3C4654), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aht20panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_aht20panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_aht20panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aht20label = lv_label_create(ui_aht20panel);
    lv_obj_set_width(ui_aht20label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aht20label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aht20label, -10);
    lv_obj_set_y(ui_aht20label, -70);
    lv_obj_set_align(ui_aht20label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aht20label, "AHT20");
    lv_obj_set_style_text_color(ui_aht20label, lv_color_hex(0x51C5B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aht20label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aht20label, &ui_font_PM30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aht20tempnum = lv_label_create(ui_aht20panel);
    lv_obj_set_width(ui_aht20tempnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aht20tempnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aht20tempnum, 40);
    lv_obj_set_y(ui_aht20tempnum, 45);
    lv_label_set_text(ui_aht20tempnum, "20℃");
    lv_obj_set_style_text_color(ui_aht20tempnum, lv_color_hex(0x52C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aht20tempnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aht20tempnum, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aht20humi = lv_img_create(ui_aht20panel);
    lv_img_set_src(ui_aht20humi, &ui_img_icon_humi_png);
    lv_obj_set_width(ui_aht20humi, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_aht20humi, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_aht20humi, -50);
    lv_obj_set_y(ui_aht20humi, 20);
    lv_obj_set_align(ui_aht20humi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aht20humi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aht20humi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_aht20humi, 120);

    ui_aht20temp = lv_img_create(ui_aht20panel);
    lv_img_set_src(ui_aht20temp, &ui_img_icon_temp_png);
    lv_obj_set_width(ui_aht20temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aht20temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aht20temp, -50);
    lv_obj_set_y(ui_aht20temp, -20);
    lv_obj_set_align(ui_aht20temp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_aht20temp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_aht20temp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_aht20temp, 140);

    ui_aht20huminum = lv_label_create(ui_aht20panel);
    lv_obj_set_width(ui_aht20huminum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aht20huminum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aht20huminum, 40);
    lv_obj_set_y(ui_aht20huminum, 85);
    lv_label_set_text(ui_aht20huminum, "50%");
    lv_obj_set_style_text_color(ui_aht20huminum, lv_color_hex(0x52C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_aht20huminum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_aht20huminum, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bmp280panel = lv_obj_create(ui_sensorpage);
    lv_obj_set_width(ui_bmp280panel, 150);
    lv_obj_set_height(ui_bmp280panel, 180);
    lv_obj_set_x(ui_bmp280panel, -5);
    lv_obj_set_y(ui_bmp280panel, 5);
    lv_obj_set_align(ui_bmp280panel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_bmp280panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_bmp280panel, lv_color_hex(0x3C4654), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bmp280panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_bmp280panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_bmp280panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bmp280label = lv_label_create(ui_bmp280panel);
    lv_obj_set_width(ui_bmp280label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bmp280label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bmp280label, 1);
    lv_obj_set_y(ui_bmp280label, -70);
    lv_obj_set_align(ui_bmp280label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bmp280label, "BMP280");
    lv_obj_set_style_text_color(ui_bmp280label, lv_color_hex(0x509EC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bmp280label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bmp280label, &ui_font_PM30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bmptempnum = lv_label_create(ui_bmp280panel);
    lv_obj_set_width(ui_bmptempnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bmptempnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bmptempnum, 40);
    lv_obj_set_y(ui_bmptempnum, 45);
    lv_label_set_text(ui_bmptempnum, "20℃");
    lv_obj_set_style_text_color(ui_bmptempnum, lv_color_hex(0x52C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bmptempnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bmptempnum, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bmppressnum = lv_label_create(ui_bmp280panel);
    lv_obj_set_width(ui_bmppressnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bmppressnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bmppressnum, 40);
    lv_obj_set_y(ui_bmppressnum, 85);
    lv_label_set_text(ui_bmppressnum, "1000Pa");
    lv_obj_set_style_text_color(ui_bmppressnum, lv_color_hex(0x52C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bmppressnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bmppressnum, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bmppress = lv_img_create(ui_bmp280panel);
    lv_img_set_src(ui_bmppress, &ui_img_icon_pressure_png);
    lv_obj_set_width(ui_bmppress, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_bmppress, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_bmppress, -50);
    lv_obj_set_y(ui_bmppress, 20);
    lv_obj_set_align(ui_bmppress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bmppress, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bmppress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bmppress, 160);

    ui_bmptemp = lv_img_create(ui_bmp280panel);
    lv_img_set_src(ui_bmptemp, &ui_img_icon_temp_png);
    lv_obj_set_width(ui_bmptemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bmptemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bmptemp, -50);
    lv_obj_set_y(ui_bmptemp, -20);
    lv_obj_set_align(ui_bmptemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bmptemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bmptemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bmptemp, 140);

    ui_bmpalti = lv_img_create(ui_bmp280panel);
    lv_img_set_src(ui_bmpalti, &ui_img_icon_altitude_png);
    lv_obj_set_width(ui_bmpalti, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_bmpalti, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_bmpalti, -50);
    lv_obj_set_y(ui_bmpalti, 60);
    lv_obj_set_align(ui_bmpalti, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bmpalti, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bmpalti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_bmpalti, 90);

    ui_bmpaltnum = lv_label_create(ui_bmp280panel);
    lv_obj_set_width(ui_bmpaltnum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bmpaltnum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bmpaltnum, 42);
    lv_obj_set_y(ui_bmpaltnum, 127);
    lv_label_set_text(ui_bmpaltnum, "100m");
    lv_obj_set_style_text_color(ui_bmpaltnum, lv_color_hex(0x52C6B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bmpaltnum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bmpaltnum, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorback = lv_imgbtn_create(ui_sensorpage);
    lv_imgbtn_set_src(ui_sensorback, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_backward_png, NULL);
    lv_obj_set_height(ui_sensorback, 32);
    lv_obj_set_width(ui_sensorback, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sensorback, 10);
    lv_obj_set_y(ui_sensorback, -10);
    lv_obj_set_align(ui_sensorback, LV_ALIGN_BOTTOM_LEFT);

    lv_obj_add_event_cb(ui_sensorback, ui_event_sensorback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sensorpage, ui_event_sensorpage, LV_EVENT_ALL, NULL);

}
