// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SETTING

#include "../ui.h"

void ui_settingpage_screen_init(void)
{
    ui_settingpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingback = lv_imgbtn_create(ui_settingpage);
    lv_imgbtn_set_src(ui_settingback, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_backward_png, NULL);
    lv_obj_set_height(ui_settingback, 32);
    lv_obj_set_width(ui_settingback, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_settingback, 10);
    lv_obj_set_y(ui_settingback, -10);
    lv_obj_set_align(ui_settingback, LV_ALIGN_BOTTOM_LEFT);

    ui_wifi = lv_obj_create(ui_settingpage);
    lv_obj_set_width(ui_wifi, 300);
    lv_obj_set_height(ui_wifi, 50);
    lv_obj_set_x(ui_wifi, 0);
    lv_obj_set_y(ui_wifi, -80);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0x3F3F3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifilist = lv_dropdown_create(ui_wifi);
    lv_dropdown_set_options(ui_wifilist, "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6");
    lv_obj_set_width(ui_wifilist, 220);
    lv_obj_set_height(ui_wifilist, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifilist, 26);
    lv_obj_set_y(ui_wifilist, 0);
    lv_obj_set_align(ui_wifilist, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifilist, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_wifilist, lv_color_hex(0x00CA83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifilist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifilist, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifilist, lv_color_hex(0x435158), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifilist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifilist, lv_color_hex(0x8BC68B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifilist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_wifilist, lv_color_hex(0x7DAF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifilist, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_wifilist), lv_color_hex(0x4E616E),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_wifilist), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_wifilist), lv_color_hex(0x2D4C58),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_wifilist), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_scanWifi = lv_imgbtn_create(ui_wifi);
    lv_imgbtn_set_src(ui_scanWifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_setting_wifi_png, NULL);
    lv_obj_set_width(ui_scanWifi, 64);
    lv_obj_set_height(ui_scanWifi, 64);
    lv_obj_set_x(ui_scanWifi, lv_pct(-44));
    lv_obj_set_y(ui_scanWifi, lv_pct(6));
    lv_obj_set_align(ui_scanWifi, LV_ALIGN_CENTER);

    ui_blkpanel = lv_obj_create(ui_settingpage);
    lv_obj_set_width(ui_blkpanel, 300);
    lv_obj_set_height(ui_blkpanel, 50);
    lv_obj_set_x(ui_blkpanel, 0);
    lv_obj_set_y(ui_blkpanel, -20);
    lv_obj_set_align(ui_blkpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_blkpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_blkpanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blkpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_blkpanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_blkpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_blkslider = lv_slider_create(ui_blkpanel);
    lv_slider_set_range(ui_blkslider, 10, 100);
    lv_slider_set_value(ui_blkslider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_blkslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_blkslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_blkslider, 300);
    lv_obj_set_height(ui_blkslider, 50);
    lv_obj_set_align(ui_blkslider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_blkslider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_blkslider, &ui_img_icon_setting_blkd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_blkslider, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_blkslider, &ui_img_icon_setting_blkl_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_blkslider, lv_color_hex(0x529BFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_blkslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_blk = lv_img_create(ui_blkpanel);
    lv_img_set_src(ui_blk, &ui_img_icon_setting_blkdd_png);
    lv_obj_set_width(ui_blk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_blk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_blk, -120);
    lv_obj_set_y(ui_blk, 0);
    lv_obj_set_align(ui_blk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blk, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumepanel = lv_obj_create(ui_settingpage);
    lv_obj_set_width(ui_volumepanel, 300);
    lv_obj_set_height(ui_volumepanel, 50);
    lv_obj_set_x(ui_volumepanel, 0);
    lv_obj_set_y(ui_volumepanel, 40);
    lv_obj_set_align(ui_volumepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_volumepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_volumepanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_volumepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_volumepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeslider = lv_slider_create(ui_volumepanel);
    lv_slider_set_range(ui_volumeslider, 10, 100);
    lv_slider_set_value(ui_volumeslider, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volumeslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volumeslider, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_volumeslider, 300);
    lv_obj_set_height(ui_volumeslider, 50);
    lv_obj_set_align(ui_volumeslider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_volumeslider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_volumeslider, &ui_img_icon_setting_blkd_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_volumeslider, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_volumeslider, &ui_img_icon_setting_blkl_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0x529BFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volumeslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_volume = lv_img_create(ui_volumepanel);
    lv_img_set_src(ui_volume, &ui_img_icon_setting_volume1_png);
    lv_obj_set_width(ui_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volume, -120);
    lv_obj_set_y(ui_volume, 0);
    lv_obj_set_align(ui_volume, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volume, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PWDINPUT = lv_obj_create(ui_settingpage);
    lv_obj_set_width(ui_PWDINPUT, 300);
    lv_obj_set_height(ui_PWDINPUT, 160);
    lv_obj_set_x(ui_PWDINPUT, 0);
    lv_obj_set_y(ui_PWDINPUT, 240);
    lv_obj_set_align(ui_PWDINPUT, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PWDINPUT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PWDINPUT, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PWDINPUT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwdkey = lv_keyboard_create(ui_PWDINPUT);
    lv_obj_set_width(ui_pwdkey, 300);
    lv_obj_set_height(ui_pwdkey, 110);
    lv_obj_set_x(ui_pwdkey, 0);
    lv_obj_set_y(ui_pwdkey, 24);
    lv_obj_set_align(ui_pwdkey, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_pwdkey, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pwdkey, lv_color_hex(0x00EE9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pwdkey, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectWifi = lv_btn_create(ui_PWDINPUT);
    lv_obj_set_width(ui_connectWifi, 40);
    lv_obj_set_height(ui_connectWifi, 30);
    lv_obj_set_x(ui_connectWifi, 122);
    lv_obj_set_y(ui_connectWifi, -53);
    lv_obj_set_align(ui_connectWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_connectWifi, lv_color_hex(0x8BC68B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwdarea = lv_textarea_create(ui_PWDINPUT);
    lv_obj_set_width(ui_pwdarea, 234);
    lv_obj_set_height(ui_pwdarea, 37);
    lv_obj_set_x(ui_pwdarea, -25);
    lv_obj_set_y(ui_pwdarea, -54);
    lv_obj_set_align(ui_pwdarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_pwdarea, "password");
    lv_obj_set_style_text_color(ui_pwdarea, lv_color_hex(0x00CA83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pwdarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_load = lv_spinner_create(ui_settingpage, 1000, 90);
    lv_obj_set_width(ui_load, 80);
    lv_obj_set_height(ui_load, 80);
    lv_obj_set_align(ui_load, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_load, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_load, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_opa(ui_load, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_load, lv_color_hex(0xC2C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_load, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_load, lv_color_hex(0x00CA83), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_load, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settingback, ui_event_settingback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifilist, ui_event_wifilist, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scanWifi, ui_event_scanWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_blkslider, ui_event_blkslider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeslider, ui_event_volumeslider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connectWifi, ui_event_connectWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingpage, ui_event_settingpage, LV_EVENT_ALL, NULL);

}
