// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_weathercpage_screen_init(void)
{
    ui_weathercpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weathercpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weathercpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weathercpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statepanel = lv_obj_create(ui_weathercpage);
    lv_obj_set_width(ui_statepanel, 289);
    lv_obj_set_height(ui_statepanel, 118);
    lv_obj_set_x(ui_statepanel, lv_pct(0));
    lv_obj_set_y(ui_statepanel, lv_pct(24));
    lv_obj_set_align(ui_statepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statepanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statepanel, lv_color_hex(0x4F4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statepanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statepanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_statepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_statepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outhumi = lv_label_create(ui_statepanel);
    lv_obj_set_width(ui_outhumi, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_outhumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outhumi, 32);
    lv_obj_set_y(ui_outhumi, 2);
    lv_obj_set_align(ui_outhumi, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_outhumi, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_outhumi, "100%");
    lv_obj_set_style_text_color(ui_outhumi, lv_color_hex(0x5CAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outhumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outhumi, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outtemp = lv_label_create(ui_statepanel);
    lv_obj_set_width(ui_outtemp, 60);
    lv_obj_set_height(ui_outtemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outtemp, 32);
    lv_obj_set_y(ui_outtemp, -34);
    lv_obj_set_align(ui_outtemp, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_outtemp, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_outtemp, "20℃");
    lv_obj_set_style_text_color(ui_outtemp, lv_color_hex(0x5CAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outtemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outtemp, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempimage2 = lv_img_create(ui_statepanel);
    lv_img_set_src(ui_tempimage2, &ui_img_icon_temp_png);
    lv_obj_set_width(ui_tempimage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempimage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempimage2, -122);
    lv_obj_set_y(ui_tempimage2, -35);
    lv_obj_set_align(ui_tempimage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempimage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempimage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_tempimage2, 100);

    ui_humiimage2 = lv_img_create(ui_statepanel);
    lv_img_set_src(ui_humiimage2, &ui_img_icon_humi_png);
    lv_obj_set_width(ui_humiimage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiimage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiimage2, -121);
    lv_obj_set_y(ui_humiimage2, 2);
    lv_obj_set_align(ui_humiimage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humiimage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humiimage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_humiimage2, 100);

    ui_pressimage2 = lv_img_create(ui_statepanel);
    lv_img_set_src(ui_pressimage2, &ui_img_icon_pressure_png);
    lv_obj_set_width(ui_pressimage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pressimage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pressimage2, -120);
    lv_obj_set_y(ui_pressimage2, 36);
    lv_obj_set_align(ui_pressimage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pressimage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_pressimage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_pressimage2, 120);

    ui_winddirimage1 = lv_img_create(ui_statepanel);
    lv_img_set_src(ui_winddirimage1, &ui_img_icon_winddir_png);
    lv_obj_set_width(ui_winddirimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_winddirimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_winddirimage1, 48);
    lv_obj_set_y(ui_winddirimage1, -35);
    lv_obj_set_align(ui_winddirimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_winddirimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_winddirimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_winddirimage1, 120);

    ui_outpress = lv_label_create(ui_statepanel);
    lv_obj_set_width(ui_outpress, 90);
    lv_obj_set_height(ui_outpress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outpress, 32);
    lv_obj_set_y(ui_outpress, 37);
    lv_obj_set_align(ui_outpress, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_outpress, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_outpress, "6260Pa");
    lv_obj_set_style_text_color(ui_outpress, lv_color_hex(0x5CAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_outpress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_outpress, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_winddir = lv_label_create(ui_statepanel);
    lv_obj_set_width(ui_winddir, 60);
    lv_obj_set_height(ui_winddir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_winddir, 208);
    lv_obj_set_y(ui_winddir, -35);
    lv_obj_set_align(ui_winddir, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_winddir, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_winddir, "北风");
    lv_obj_set_style_text_color(ui_winddir, lv_color_hex(0x5CAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_winddir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_winddir, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_windscaleimage1 = lv_img_create(ui_statepanel);
    lv_img_set_src(ui_windscaleimage1, &ui_img_icon_windspeed_png);
    lv_obj_set_width(ui_windscaleimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_windscaleimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_windscaleimage1, 48);
    lv_obj_set_y(ui_windscaleimage1, -1);
    lv_obj_set_align(ui_windscaleimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_windscaleimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_windscaleimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_windscaleimage1, 120);

    ui_windscale = lv_label_create(ui_statepanel);
    lv_obj_set_width(ui_windscale, 60);
    lv_obj_set_height(ui_windscale, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_windscale, 208);
    lv_obj_set_y(ui_windscale, 0);
    lv_obj_set_align(ui_windscale, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_windscale, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_windscale, "2级");
    lv_obj_set_style_text_color(ui_windscale, lv_color_hex(0x5CAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_windscale, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_windscale, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_visimage1 = lv_img_create(ui_statepanel);
    lv_img_set_src(ui_visimage1, &ui_img_icon_vis_png);
    lv_obj_set_width(ui_visimage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_visimage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_visimage1, 50);
    lv_obj_set_y(ui_visimage1, 36);
    lv_obj_set_align(ui_visimage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_visimage1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_visimage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_visimage1, 120);

    ui_vis = lv_label_create(ui_statepanel);
    lv_obj_set_width(ui_vis, 60);
    lv_obj_set_height(ui_vis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vis, 208);
    lv_obj_set_y(ui_vis, 38);
    lv_obj_set_align(ui_vis, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_vis, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_vis, "2KM");
    lv_obj_set_style_text_color(ui_vis, lv_color_hex(0x5CAEFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vis, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_weathercpage);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -17);
    lv_obj_set_y(ui_time, -87);
    lv_obj_set_align(ui_time, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_time, "18:47");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x00A3A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_PM40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weathericon = lv_img_create(ui_weathercpage);
    lv_img_set_src(ui_weathericon, &ui_img_icon_weather_mai_png);
    lv_obj_set_width(ui_weathericon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weathericon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weathericon, -101);
    lv_obj_set_y(ui_weathericon, -57);
    lv_obj_set_align(ui_weathericon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_weathericon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_weathericon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_date = lv_label_create(ui_weathercpage);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -17);
    lv_obj_set_y(ui_date, -19);
    lv_obj_set_align(ui_date, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_date, "24/4/24");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_weathercpage);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, -17);
    lv_obj_set_y(ui_week, -51);
    lv_obj_set_align(ui_week, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_week, "周四");
    lv_obj_set_style_text_color(ui_week, lv_color_hex(0xFFBF2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_week, &ui_font_SY20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherstate = lv_label_create(ui_weathercpage);
    lv_obj_set_width(ui_weatherstate, 30);
    lv_obj_set_height(ui_weatherstate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherstate, -166);
    lv_obj_set_y(ui_weatherstate, -57);
    lv_obj_set_align(ui_weatherstate, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_weatherstate, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_weatherstate, "多云大雨");
    lv_obj_set_style_text_color(ui_weatherstate, lv_color_hex(0x57F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherstate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherstate, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_feeltemp = lv_label_create(ui_weathercpage);
    lv_obj_set_width(ui_feeltemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_feeltemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_feeltemp, -166);
    lv_obj_set_y(ui_feeltemp, -34);
    lv_obj_set_align(ui_feeltemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_feeltemp, "20℃");
    lv_obj_set_style_text_color(ui_feeltemp, lv_color_hex(0x7557FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_feeltemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_feeltemp, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_category = lv_label_create(ui_weathercpage);
    lv_obj_set_width(ui_category, 36);
    lv_obj_set_height(ui_category, 19);
    lv_obj_set_x(ui_category, -166);
    lv_obj_set_y(ui_category, -83);
    lv_obj_set_align(ui_category, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_category, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_category, "优");
    lv_obj_set_style_text_color(ui_category, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_category, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_category, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_category, &ui_font_SY15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_category, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_category, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_category, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_category, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_category, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_category, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_category, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherback = lv_imgbtn_create(ui_weathercpage);
    lv_imgbtn_set_src(ui_weatherback, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_backward_png, NULL);
    lv_obj_set_height(ui_weatherback, 32);
    lv_obj_set_width(ui_weatherback, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_weatherback, 10);
    lv_obj_set_y(ui_weatherback, 10);
    lv_obj_set_align(ui_weatherback, LV_ALIGN_TOP_LEFT);

    ui_weatherfor = lv_imgbtn_create(ui_weathercpage);
    lv_imgbtn_set_src(ui_weatherfor, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_forward_png, NULL);
    lv_obj_set_height(ui_weatherfor, 32);
    lv_obj_set_width(ui_weatherfor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_weatherfor, 80);
    lv_obj_set_y(ui_weatherfor, 10);
    lv_obj_set_align(ui_weatherfor, LV_ALIGN_TOP_LEFT);

    lv_obj_add_event_cb(ui_weatherfor, ui_event_weatherfor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weatherback, ui_event_weatherback, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_weathercpage, ui_event_weathercpage, LV_EVENT_ALL, NULL);

}
